[package]
name = "todo-app"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-cors = "0.7.1"
actix-web = "4.11.0"
rusqlite = { version = "0.29", features = ["bundled"] }
serde = "1.0.219"
serde_json = "1.0.140"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "time"] }
